drop table if exists bag CASCADE ;
drop table if exists item CASCADE ;
create table bag (id bigint generated by default as identity, list_name varchar(255) not null, primary key (id));
create table item (id bigint generated by default as identity, item_name varchar(255) not null, price double not null, bag_id bigint, primary key (id));
alter table item add constraint FKlfuv8wv3ak8ivk4m2t63xcig7 foreign key (bag_id) references bag on delete cascade;